### ISSUE TITLE
UnicodeDecodeError - niektoré vgi súbory nie sú kompletne skonvertované - problém s encod-ovaním

### ISSUE THREAD

**Issue by stanom** [imincik/kataster-import#6]
Niektoré vgi súbory sa nepodarí skonvertovať kompletne, konvertovanie končí napr. takto:
```
Traceback (most recent call last):
  File "/kataster-import/./kt-vgi2shp", line 249, in <module>
    main()
  File "/kataster-import/./kt-vgi2shp", line 232, in main
    zapisovac.uloz(objekt_data)
  File "/kataster-import/katastertools/VgiShp/data.py", line 602, in uloz
    self.__zapisovac_vrstvy[vrstva.lower()].uloz(data)
  File "/kataster-import/katastertools/VgiShp/data.py", line 511, in uloz
    for feature in self.features(data):
  File "/kataster-import/katastertools/VgiShp/data.py", line 495, in features
    f.SetField(atribut, hodnota.encode(self.kodovanie))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 3: ordinal not in range(128)
```

Asi narazí na nekorektný znak, a konvertovanie dát z daného vgi súboru sa tým ukončí.

Vytiahnutie blokov z logu, kde nastala chyba:
`grep -iv '\(^\s \|Warning\|^INFO: B \|^INFO: V \|^INFO: R \)' /data/VKM_KN_28_04_2017/log/vgi-kn-sql.log.bkp |sed -n '/ZACIATOK KONVERZIE/{ N;N;N;N;/Traceback/p }'`

**Comment by stanom** [comment]
prikladám zoznam jedinečných znakov, na ktorých konvert celoslovenskych vgi súborov zlyhával:
`grep 'UnicodeDecodeError' /data/VKM_KN_28_04_2017/log/vgi-kn-sql.log |awk -F" " '{print $7}' | sort |uniq`
0x82
0x8e
0x90
0x95
0x96
0x97
0xa0
0xa1
0xa6
0xac
0xb5
0xd2
0xd5
0xd6
0xdd
0xe1
0xe6
0xe7
0xe9
0xed


Sú to znaky  zo znakovej sady CP852:
`grep 'UnicodeDecodeError' /data/VKM_KN_28_04_2017/log/vgi-kn-sql.log |awk -F" " '{print $7}' | sort |uniq | sed 's/0x/\\x/g' |awk '{print "printf \""$1"\" |iconv -f cp852 -t utf8"}'`
é
Ä
É
Ľ
ľ
Ś
á
í
Ž
Č
Á
Ď
Ň
Í
Ţ
ß
Š
š
Ú

**Comment by stanom** [comment]
v ktorych VGI suboroch tento problem nastal:
`grep -iv '\(^\s \|Warning\|^INFO: B \|^INFO: V \|^INFO: R \)' /data/VKM_KN_28_04_2017/log/vgi-kn-sql.log.bkp |sed -n '/ZACIATOK KONVERZIE/{ N;N;N;N;/Traceback/p }'`
=> v 52 VGI suboroch

**Comment by stanom** [comment]
v zdrojových VGI súboroch je mix CP1250 a CP852 znakových sád
pythonovské skripty konvertujú do utf8 cp1250 znaky sú ok, na cp852 znakoch konverzia zlyhá
`grep Str /data/VKM_KN_28_04_2017/vgi/KN848298_3_1_I.vgi |iconv -f cp1250 -t utf8`
=>
&T 328951.63 1198295.90 'Str §e pod Tatrami' D=1 F=2 H=4.8 K=2
&T 329078.32 1198619.95 'Str §ske n mestie' D=1 F=2 H=1.3 K=1
&T 329414.69 1198291.05 'Str §e pod Tatrami' D=1 F=2 H=4.8 K=2
&T 329294.04 1198865.27 'Str §e pod Tatrami' D=1 F=2 H=4.8 K=2
&T 328845.10 1199165.51 'Str §e pod Tatrami' D=1 F=2 H=4.8 K=2
&T 327821.10 1198688.82 'Str §e' D=1 F=2 H=2.2 K=1
&A PPU=Stráže pod Tatrami
&A OBEC=Stráže pod Tatrami
&A HKU=Stráže pod Tatrami


**Návrh:**
vyhľadať všetky non-ascii znaky:

`sed -n '/\x82\|\x8e\|\x90\|\x95\|\x96\|\x97\|\xa0\|\xa1\|\xa6\|\xac\|\xb5\|\xd2\|\xd5\|\xd6\|\xdd\|\xe1\|\xe6\|\xe7\|\xe9\|\xed/p' /data/VKM_KN_28_04_2017/vgi/KN825107_1_2.vgi`
Následne ich skonvertovať.
 Ak narazí konvertor na non-ascii znak, (pravdepodobne sa jedná o znak cp852 kódovania), tak ho skonvertnut na utf8, napr. ako 
`sed -n '/\xb5/p' /data/VKM_KN_28_04_2017/vgi/KN825107_1_2.vgi |iconv -f cp852 -t utf8`
"&A HKU=BECKOVSKµ VIESKA" -> "&A HKU=BECKOVSKÁ VIESKA"

(http://www.idautomation.com/product-support/ascii-chart-char-set.html)

**Comment by stanom** [comment]
riešením môže byť knižnica [ftfy](https://github.com/LuminosoInsight/python-ftfy)
`pip install ftfy`

ukážka konverzie: `ftfy -e cp852 /tmp/KN848298_3_1_I.vgi |grep Str`
```
&T 328845.10 1199165.51 'Stráže pod Tatrami' D=1 F=2 H=4.8 K=2
&T 329294.04 1198865.27 'Stráže pod Tatrami' D=1 F=2 H=4.8 K=2
&T 329414.69 1198291.05 'Stráže pod Tatrami' D=1 F=2 H=4.8 K=2
&T 329078.32 1198619.95 'Strážske námestie' D=1 F=2 H=1.3 K=1
&T 328951.63 1198295.90 'Stráže pod Tatrami' D=1 F=2 H=4.8 K=2
```
